import { supabase } from '../client';
import type {
  Household,
  HouseholdInsert,
  HouseholdUpdate,
  Patient,
  PatientInsert,
  Caregiver,
  CaregiverInsert,
  SubscriptionStatus,
} from '@memoguard/shared';

/**
 * Create a new household with patient and caregiver records
 * This is used during onboarding
 */
export async function createHousehold(
  caregiverId: string,
  caregiverData: Omit<CaregiverInsert, 'id' | 'household_id'>,
  patientData: Omit<PatientInsert, 'household_id'>,
  householdData?: HouseholdInsert
): Promise<{ household: Household; patient: Patient; caregiver: Caregiver }> {
  // Create household first (care_code is auto-generated by trigger)
  const { data: household, error: householdError } = await supabase
    .from('households')
    .insert({
      timezone: householdData?.timezone || 'UTC',
      language: householdData?.language || 'en',
      country: householdData?.country,
    })
    .select()
    .single();

  if (householdError) throw householdError;

  // Create patient record
  const { data: patient, error: patientError } = await supabase
    .from('patients')
    .insert({
      household_id: household.id,
      name: patientData.name,
      date_of_birth: patientData.date_of_birth,
      dementia_type: patientData.dementia_type,
      stage: patientData.stage,
      home_address_formatted: patientData.home_address_formatted,
      home_latitude: patientData.home_latitude,
      home_longitude: patientData.home_longitude,
      medications: patientData.medications || [],
      biography: patientData.biography || {},
      photos: patientData.photos || [],
      wake_time: patientData.wake_time,
      sleep_time: patientData.sleep_time,
      emergency_number: patientData.emergency_number,
    })
    .select()
    .single();

  if (patientError) throw patientError;

  // Create caregiver record
  const { data: caregiver, error: caregiverError } = await supabase
    .from('caregivers')
    .insert({
      id: caregiverId,
      household_id: household.id,
      name: caregiverData.name,
      email: caregiverData.email,
      relationship: caregiverData.relationship,
      role: 'primary',
      permissions: caregiverData.permissions || { can_edit_plan: true, receives_alerts: true },
      language_preference: caregiverData.language_preference || 'en',
      notification_preferences: caregiverData.notification_preferences || {
        safety_alerts: true,
        daily_summary: true,
        email_notifications: true,
      },
    })
    .select()
    .single();

  if (caregiverError) throw caregiverError;

  return { household, patient, caregiver };
}

/**
 * Get a household by ID with the associated patient
 */
export async function getHousehold(
  householdId: string
): Promise<Household & { patient: Patient }> {
  const { data, error } = await supabase
    .from('households')
    .select(
      `
      *,
      patient:patients(*)
    `
    )
    .eq('id', householdId)
    .single();

  if (error) throw error;

  // Flatten the result
  const { patient: patients, ...household } = data;
  return {
    ...household,
    patient: Array.isArray(patients) ? patients[0] : patients,
  };
}

/**
 * Validate a care code and return the household if valid
 */
export async function validateCareCode(code: string): Promise<Household | null> {
  const { data, error } = await supabase
    .from('households')
    .select('*')
    .eq('care_code', code)
    .single();

  if (error) {
    if (error.code === 'PGRST116') {
      // No rows returned
      return null;
    }
    throw error;
  }

  return data;
}

/**
 * Generate a unique 6-digit care code with collision checking.
 * Retries up to 10 times if the generated code already exists.
 */
export async function generateUniqueCareCode(): Promise<string> {
  for (let attempt = 0; attempt < 10; attempt++) {
    // Use crypto for better randomness when available
    let randomVal: number;
    if (typeof globalThis.crypto !== 'undefined' && globalThis.crypto.getRandomValues) {
      const array = new Uint32Array(1);
      globalThis.crypto.getRandomValues(array);
      randomVal = array[0];
    } else {
      randomVal = Math.floor(Math.random() * 4294967296);
    }
    const code = (100000 + (randomVal % 900000)).toString();

    // Check for collision
    const { data } = await supabase
      .from('households')
      .select('id')
      .eq('care_code', code)
      .maybeSingle();

    if (!data) return code;
  }

  throw new Error('Failed to generate unique care code after 10 attempts');
}

/**
 * Regenerate care code for a household
 */
export async function regenerateCareCode(householdId: string): Promise<string> {
  const newCode = await generateUniqueCareCode();

  const { data, error } = await supabase
    .from('households')
    .update({ care_code: newCode })
    .eq('id', householdId)
    .select('care_code')
    .single();

  if (error) throw error;

  return data.care_code;
}

/**
 * Update household subscription status
 */
export async function updateSubscription(
  householdId: string,
  status: SubscriptionStatus,
  platform?: 'web' | 'ios' | 'android'
): Promise<Household> {
  const updates: HouseholdUpdate = {
    subscription_status: status,
  };

  if (platform) {
    updates.subscription_platform = platform;
  }

  const { data, error } = await supabase
    .from('households')
    .update(updates)
    .eq('id', householdId)
    .select()
    .single();

  if (error) throw error;

  return data;
}

/**
 * Get household by care code (for patient device pairing)
 */
export async function getHouseholdByCareCode(
  code: string
): Promise<(Household & { patient: Patient }) | null> {
  const { data, error } = await supabase
    .from('households')
    .select(
      `
      *,
      patient:patients(*)
    `
    )
    .eq('care_code', code)
    .single();

  if (error) {
    if (error.code === 'PGRST116') {
      return null;
    }
    throw error;
  }

  const { patient: patients, ...household } = data;
  return {
    ...household,
    patient: Array.isArray(patients) ? patients[0] : patients,
  };
}
