/**
 * CRISIS RESPONSE TEMPLATES
 * These are STATIC, pre-written responses — NOT generated by AI.
 * They are shown immediately when a RED trigger is detected.
 * The AI model is NOT called at all for RED classifications.
 */

export interface CrisisResource {
  name: string;
  action: string;
  type: 'emergency' | 'crisis' | 'protection' | 'support' | 'info';
  priority: number;
}

export interface CrisisResponse {
  title: string;
  message: string;
  resources: CrisisResource[];
  aiFollowUp: boolean;
  logLevel: 'critical' | 'high';
  notifyCaregiver: boolean;
}

export const CRISIS_RESPONSES: Record<string, CrisisResponse> = {
  CRISIS_SELF_HARM: {
    title: "We're here for you",
    message:
      "It sounds like you're going through an incredibly difficult time. You don't have to face this alone. Please reach out to someone who can help right now.",
    resources: [
      {
        name: 'Emergency Services',
        action: 'Call 112 (EU) or 911 (US)',
        type: 'emergency',
        priority: 1,
      },
      {
        name: 'Crisis Text Line',
        action: 'Text HOME to 741741 (US) or text SHOUT to 85258 (UK)',
        type: 'crisis',
        priority: 2,
      },
      {
        name: 'Telefonseelsorge (Germany)',
        action: 'Call 0800 111 0 111 or 0800 111 0 222 (free, 24/7)',
        type: 'crisis',
        priority: 2,
      },
      {
        name: "Alzheimer's Association 24/7 Helpline",
        action: 'Call 1-800-272-3900 (US)',
        type: 'support',
        priority: 3,
      },
    ],
    aiFollowUp: false,
    logLevel: 'critical',
    notifyCaregiver: false,
  },

  CRISIS_ABUSE: {
    title: 'Everyone deserves to be safe',
    message:
      "Caring for someone with dementia is one of the hardest things a person can do. If you're worried about someone's safety — or your own ability to cope — there are people who can help without judgment.",
    resources: [
      {
        name: 'Adult Protective Services (US)',
        action: 'Call 1-800-677-1116 (Eldercare Locator)',
        type: 'protection',
        priority: 1,
      },
      {
        name: 'Pflegetelefon (Germany)',
        action: 'Call 030 20179131 (care counseling hotline)',
        type: 'support',
        priority: 2,
      },
      {
        name: "Alzheimer's Association 24/7 Helpline",
        action: 'Call 1-800-272-3900',
        type: 'support',
        priority: 3,
      },
      {
        name: 'Respite Care Information',
        action: 'Learn about temporary relief options for caregivers',
        type: 'info',
        priority: 4,
      },
    ],
    aiFollowUp: false,
    logLevel: 'critical',
    notifyCaregiver: false,
  },

  CRISIS_EMERGENCY: {
    title: 'This needs immediate attention',
    message:
      'This sounds like it may be an emergency. Please call for help right away.',
    resources: [
      {
        name: 'Emergency Services',
        action: 'Call 112 (EU) or 911 (US) immediately',
        type: 'emergency',
        priority: 1,
      },
      {
        name: 'Poison Control (if medication issue)',
        action: 'Call 112 (EU) or 1-800-222-1222 (US)',
        type: 'emergency',
        priority: 2,
      },
    ],
    aiFollowUp: false,
    logLevel: 'critical',
    notifyCaregiver: true,
  },

  CRISIS_CAREGIVER: {
    title: 'Your feelings matter',
    message:
      "What you're feeling is a natural response to an incredibly demanding situation. Caregiver burnout is real, and it doesn't mean you've failed — it means you need and deserve support.",
    resources: [
      {
        name: "Alzheimer's Association 24/7 Helpline",
        action: 'Call 1-800-272-3900 — trained staff available around the clock',
        type: 'support',
        priority: 1,
      },
      {
        name: 'Pflegestutzpunkte (Germany)',
        action: 'Find your local care support center at pflegestuetzpunkte-online.de',
        type: 'support',
        priority: 2,
      },
      {
        name: 'Respite Care',
        action: 'Temporary care so you can take a break — you deserve it',
        type: 'info',
        priority: 3,
      },
      {
        name: 'Caregiver Support Groups',
        action: 'Connect with others who understand what you\'re going through',
        type: 'info',
        priority: 4,
      },
    ],
    aiFollowUp: true,
    logLevel: 'high',
    notifyCaregiver: false,
  },
};
