const fs = require('fs');
const path = require('path');

// Danish translations for all 1361 gameLabels
const daTranslations = {
  "add_a_bow": "Sæt en sløjfe på",
  "add_garlic": "Tilsæt hvidløg",
  "add_honey": "Tilsæt honning",
  "add_milk": "Tilsæt mælk",
  "add_shampoo": "Tilsæt shampoo",
  "add_soap": "Tilsæt sæbe",
  "add_tea_bag": "Læg en tepose i",
  "add_to_pot": "Kom i gryden",
  "add_tomatoes": "Tilsæt tomater",
  "add_water": "Tilsæt vand",
  "adult": "Voksen",
  "aeroplane": "Flyver",
  "after_the_rain": "Efter regnen",
  "afternoon": "Eftermiddag",
  "afternoon_tea": "Eftermiddagsthe",
  "airport": "Lufthavn",
  "alarm_clock": "Vækkeur",
  "ambulance": "Ambulance",
  "anchor": "Anker",
  "animals": "Dyr",
  "answer_it": "Svar på det",
  "ant": "Myre",
  "antarctica": "Antarktis",
  "antiseptic": "Antiseptisk middel",
  "apple": "Æble",
  "aquarium": "Akvarium",
  "arrive_at_airport": "Ankom til lufthavnen",
  "arrow": "Pil",
  "art_supplies": "Kunstartikler",
  "astronaut": "Astronaut",
  "at_night": "Om natten",
  "attach_a_file": "Vedhæft en fil",
  "audience_claps": "Publikum klapper",
  "australia": "Australien",
  "autumn": "Efterår",
  "autumn_leaves": "Efterårsblade",
  "autumn_things": "Efterårsting",
  "baby": "Baby",
  "baby_bottle": "Sutteflaske",
  "baby_items": "Babyting",
  "backpack": "Rygsæk",
  "bagel": "Bagel",
  "bags": "Tasker",
  "baguette": "Baguette",
  "bake_bread": "Bag brød",
  "baked_goods": "Bagværk",
  "bakery": "Bageri",
  "ball": "Bold",
  "ballet": "Ballet",
  "balloon": "Ballon",
  "balloons": "Balloner",
  "balls": "Bolde",
  "banana": "Banan",
  "bandage": "Bandage",
  "bank": "Bank",
  "basketball": "Basketball",
  "bat": "Flagermus",
  "bath": "Bad",
  "bathroom": "Badeværelse",
  "bathroom_items": "Badeværelsesting",
  "bathtub": "Badekar",
  "beach": "Strand",
  "beach_day": "Stranddag",
  "beach_things": "Strandting",
  "bear": "Bjørn",
  "beautiful_painting": "Smukt maleri",
  "bed": "Seng",
  "bedroom": "Soveværelse",
  "bedside_book": "Sengebog",
  "bedtime": "Sengetid",
  "bedtime_story": "Godnathistorie",
  "bedtime_things": "Sengetidsting",
  "bee": "Bi",
  "beer": "Øl",
  "bees_buzzing": "Bier summer",
  "bell": "Klokke",
  "bell_rings": "Klokken ringer",
  "berries": "Bær",
  "bib": "Hagesmæk",
  "bicycle": "Cykel",
  "bin": "Skraldespand",
  "bird": "Fugl",
  "birds": "Fugle",
  "birthday": "Fødselsdag",
  "birthday_cake": "Fødselsdagskage",
  "birthday_party": "Fødselsdagsfest",
  "blanket": "Tæppe",
  "blossom": "Blomstring",
  "blow_out_candles": "Pust lysene ud",
  "blue": "Blå",
  "blueberry": "Blåbær",
  "board_game": "Brætspil",
  "board_games": "Brætspil",
  "board_the_plane": "Gå ombord på flyet",
  "boil_the_kettle": "Kog vand i kedlen",
  "bolt": "Bolt",
  "bone": "Knogle",
  "book": "Bog",
  "book_tickets": "Bestil billetter",
  "bookmark": "Bogmærke",
  "books": "Bøger",
  "boot": "Støvle",
  "boots": "Støvler",
  "bottle": "Flaske",
  "bouquet": "Buket",
  "bow": "Sløjfe",
  "bowl_spoon": "Skål og ske",
  "box": "Kasse",
  "bread": "Brød",
  "bread_is_ready": "Brødet er færdigt",
  "break_chocolate": "Bræk chokoladen",
  "breakfast": "Morgenmad",
  "breakfast_foods": "Morgenmadsmad",
  "broccoli": "Broccoli",
  "broom": "Kost",
  "brush": "Børste",
  "brush_teeth": "Børst tænder",
  "bucket": "Spand",
  "bud": "Knop",
  "build_a_snowman": "Byg en snemand",
  "build_snowman": "Byg snemand",
  "building_a_house": "Bygge et hus",
  "building_blocks": "Byggeklodser",
  "buildings": "Bygninger",
  "bus": "Bus",
  "bus_stop": "Busstoppested",
  "butcher": "Slagter",
  "butter": "Smør",
  "butterfly": "Sommerfugl",
  "button": "Knap",
  "button_is_fixed": "Knappen er sat på",
  "buttons": "Knapper",
  "buy_new_outfit": "Køb nyt tøj",
  "buy_presents": "Køb gaver",
  "buy_vegetables": "Køb grøntsager",
  "cabinet": "Skab",
  "caf": "Café",
  "cake": "Kage",
  "cake_slice": "Kagesnit",
  "cakes": "Kager",
  "calendar": "Kalender",
  "camera": "Kamera",
  "campfire": "Lejrbål",
  "camping": "Camping",
  "candle": "Stearinlys",
  "candles": "Stearinlys",
  "canoe": "Kano",
  "canvas": "Lærred",
  "cap": "Kasket",
  "car": "Bil",
  "carrot": "Gulerod",
  "cast_the_line": "Kast snøren ud",
  "castle": "Slot",
  "cat": "Kat",
  "cat_bed": "Katteseng",
  "cat_caf": "Katcafé",
  "cat_litter": "Kattegrus",
  "caterpillar": "Larve",
  "celebration_things": "Festting",
  "cereal": "Morgenmadsprodukter",
  "chair": "Stol",
  "check_in_mirror": "Tjek i spejlet",
  "check_spelling": "Tjek stavning",
  "cheese": "Ost",
  "chef": "Kok",
  "cherry": "Kirsebær",
  "cherry_blossom": "Kirsebærblomst",
  "chestnut": "Kastanje",
  "chick_grows_up": "Kyllingen vokser op",
  "chick_hatches": "Kyllingen klækkes",
  "chicken": "Kylling",
  "chicks": "Kyllinger",
  "chilli_pepper": "Chilipeber",
  "chocolate": "Chokolade",
  "chocolate_factory": "Chokoladefabrik",
  "choir": "Kor",
  "choose_a_song": "Vælg en sang",
  "choose_a_toy": "Vælg et legetøj",
  "choose_destination": "Vælg destination",
  "choose_food": "Vælg mad",
  "chop_onion": "Hak løg",
  "chop_onions": "Hak løg",
  "chop_potatoes": "Hak kartofler",
  "chop_vegetables": "Hak grøntsager",
  "chopsticks": "Spisepinde",
  "christmas": "Jul",
  "christmas_day": "Juledag",
  "chrysalis": "Puppe",
  "church": "Kirke",
  "cinema": "Biograf",
  "circle": "Cirkel",
  "circus": "Cirkus",
  "circus_tent": "Cirkustelt",
  "city": "By",
  "classroom": "Klasseværelse",
  "clean_house": "Gør rent i huset",
  "cleaning_items": "Rengøringsartikler",
  "climbing": "Klatring",
  "clock": "Ur",
  "clothes": "Tøj",
  "clothing": "Beklædning",
  "cloud": "Sky",
  "clown": "Klovn",
  "coat": "Frakke",
  "coconut": "Kokosnød",
  "coffee": "Kaffe",
  "coin": "Mønt",
  "cold": "Koldt",
  "cold_drink": "Kold drik",
  "cold_drinks": "Kolde drikke",
  "cold_things": "Kolde ting",
  "collect_washing": "Saml vasketøj",
  "coloured_pencils": "Farveblyanter",
  "colours": "Farver",
  "comb_hair": "Red håret",
  "compass": "Kompas",
  "concert": "Koncert",
  "conkers": "Kastanjer",
  "cook_a_lovely_meal": "Lav et dejligt måltid",
  "cook_dinner": "Lav aftensmad",
  "cook_in_pan": "Steg på panden",
  "cookbook": "Kogebog",
  "cooking": "Madlavning",
  "coral_reef": "Koralrev",
  "corn": "Majs",
  "cough_syrup": "Hostesaft",
  "courgette": "Squash",
  "cow": "Ko",
  "crab": "Krabbe",
  "crack_eggs": "Slå æg ud",
  "crayon": "Farvekridt",
  "cricket": "Cricket",
  "crocodile": "Krokodille",
  "croissant": "Croissant",
  "crooner": "Sanger",
  "crossword": "Krydsord",
  "crown": "Krone",
  "crumple_paper": "Krøl papir",
  "cucumber": "Agurk",
  "cup": "Kop",
  "cup_of_tea": "Kop te",
  "cupboard": "Skab",
  "cupcake": "Cupcake",
  "curtain": "Gardin",
  "cut": "Klip",
  "cut_out_crossword": "Klip krydsord ud",
  "cut_the_cake": "Skær kagen",
  "cutlery": "Bestik",
  "daffodils": "Påskeliljer",
  "dairy": "Mejeriprodukter",
  "daisy": "Tusindfryd",
  "dance_along": "Dans med",
  "dancing": "Dans",
  "dark": "Mørkt",
  "day_at_work": "Dag på arbejde",
  "daytime": "Dagtid",
  "december_arrives": "December kommer",
  "decorations": "Pynt",
  "dentist": "Tandlæge",
  "desert": "Ørken",
  "desserts": "Desserter",
  "diamond": "Diamant",
  "dig_a_hole": "Grav et hul",
  "dinner": "Aftensmad",
  "dinner_party": "Middagsselskab",
  "dip_strawberries": "Dyp jordbær",
  "diy_tools": "Gør-det-selv-værktøj",
  "do_the_shopping": "Gør indkøb",
  "doctor": "Læge",
  "dog": "Hund",
  "dog_barks": "Hunden gør",
  "dog_is_dirty": "Hunden er beskidt",
  "dog_sits_and_takes_it": "Hunden sidder stille",
  "dogs": "Hunde",
  "dolphin": "Delfin",
  "door_bell": "Dørklokke",
  "doughnut": "Doughnut",
  "dress": "Kjole",
  "dressing_gown": "Morgenkåbe",
  "drinks": "Drikkevarer",
  "drive_to_new_house": "Kør til det nye hus",
  "drive_to_park": "Kør til parken",
  "drive_to_shops": "Kør hen til butikkerne",
  "drum": "Tromme",
  "drums": "Trommer",
  "dry_off_and_get_dressed": "Tør dig af og tag tøj på",
  "dry_on_line": "Tør på snoren",
  "dustpan": "Fejebakke",
  "eagle": "Ørn",
  "easter": "Påske",
  "eat_breakfast": "Spis morgenmad",
  "eat_dinner": "Spis aftensmad",
  "eat_pizza": "Spis pizza",
  "egg": "Æg",
  "egg_starts_to_crack": "Ægget begynder at revne",
  "eggs": "Æg",
  "elephant": "Elefant",
  "emergency_vehicles": "Udrykningskøretøjer",
  "enjoy_lemonade": "Nyd lemonade",
  "enjoy_pancakes": "Nyd pandekager",
  "enjoy_the_cake": "Nyd kagen",
  "enjoy_the_picnic": "Nyd picnicen",
  "enjoy_the_spring": "Nyd foråret",
  "enjoy_the_treat": "Nyd godbidden",
  "evening_comes": "Aftenen kommer",
  "eyes": "Øjne",
  "eyes_get_heavy": "Øjnene bliver tunge",
  "fairy_lights": "Lyskæde",
  "fairy_tale": "Eventyr",
  "fall_asleep": "Fald i søvn",
  "falling_leaves": "Faldende blade",
  "farm": "Gård",
  "farm_animals": "Bondegårdsdyr",
  "farmer": "Landmand",
  "feeding_time": "Fodertid",
  "feel_a_tug": "Mærk et ryk",
  "feel_sleepy": "Føl dig søvnig",
  "feeling_ill": "Føler sig dårlig",
  "ferry": "Færge",
  "fill_bucket": "Fyld spanden",
  "fill_the_bath": "Fyld badekarret",
  "fill_the_bucket": "Fyld spanden",
  "fill_the_sink": "Fyld vasken",
  "find_a_film": "Find en film",
  "find_shells": "Find muslingeskaller",
  "find_the_button": "Find knappen",
  "find_the_key": "Find nøglen",
  "finish_scarf": "Gør tørklædet færdigt",
  "fire": "Ild",
  "fire_engine": "Brandbil",
  "fire_extinguisher": "Ildslukker",
  "fire_station": "Brandstation",
  "fireplace": "Pejs",
  "first_aid_box": "Førstehjælpskasse",
  "fish": "Fisk",
  "fish_swims": "Fisken svømmer",
  "fish_treats": "Fiskegodbidder",
  "fishing": "Fiskeri",
  "fishing_rod": "Fiskestang",
  "fizzy_drinks": "Sodavand",
  "flip_flop": "Klipklap",
  "flip_pancake": "Vend pandekagen",
  "flower": "Blomst",
  "flower_bed": "Blomsterbed",
  "flower_pot": "Blomsterkrukke",
  "flowers": "Blomster",
  "flowers_bloom": "Blomsterne springer ud",
  "fly_to_holiday": "Flyv på ferie",
  "fly_to_spain": "Flyv til Spanien",
  "flying_saucer": "Flyvende tallerken",
  "folder": "Mappe",
  "folding": "Foldning",
  "food": "Mad",
  "foot": "Fod",
  "football": "Fodbold",
  "football_match": "Fodboldkamp",
  "footwear": "Fodtøj",
  "for_the_cat": "Til katten",
  "for_the_dog": "Til hunden",
  "forest": "Skov",
  "fox": "Ræv",
  "frame": "Ramme",
  "france": "Frankrig",
  "fridge": "Køleskab",
  "fried_egg": "Spejlæg",
  "frog": "Frø",
  "front_door": "Hoveddør",
  "fruits": "Frugter",
  "frying_pan": "Stegepande",
  "funeral": "Begravelse",
  "furniture": "Møbler",
  "garage": "Garage",
  "garden": "Have",
  "garden_in_summer": "Have om sommeren",
  "garden_items": "Haveting",
  "gardener": "Gartner",
  "gardening": "Havearbejde",
  "gather_ingredients": "Saml ingredienserne",
  "gear": "Udstyr",
  "geography": "Geografi",
  "germany": "Tyskland",
  "get_a_biscuit": "Hent en kiks",
  "get_a_haircut": "Få klippet hår",
  "get_a_pencil": "Hent en blyant",
  "get_a_spoon": "Hent en ske",
  "get_a_treat": "Hent en godbid",
  "get_an_album": "Hent et album",
  "get_car_keys": "Hent bilnøglerne",
  "get_changed": "Skift tøj",
  "get_compost": "Hent kompost",
  "get_dressed": "Tag tøj på",
  "get_firewood": "Hent brænde",
  "get_ice_cubes": "Hent isterninger",
  "get_needles": "Hent strikkepinde",
  "get_paints_ready": "Gør malersagerne klar",
  "get_sponge": "Hent en svamp",
  "get_the_lead": "Hent snoren",
  "get_the_paper": "Hent avisen",
  "get_watercolours": "Hent vandfarver",
  "get_wool": "Hent garn",
  "get_your_coat": "Tag din frakke",
  "gift": "Gave",
  "give_as_gift": "Giv som gave",
  "give_it_sun": "Giv den sol",
  "give_the_present": "Giv gaven",
  "glasses": "Briller",
  "globe": "Globus",
  "gloves": "Handsker",
  "go_for_a_run": "Gå en tur løbende",
  "go_for_a_walk": "Gå en tur",
  "go_home": "Gå hjem",
  "go_on_holiday": "Tag på ferie",
  "go_out": "Gå ud",
  "go_outside": "Gå udenfor",
  "go_running": "Løb en tur",
  "go_shopping": "Gå og handle",
  "go_swimming": "Gå og svømme",
  "go_to_barber": "Gå til frisøren",
  "go_to_beach": "Gå til stranden",
  "go_to_bed": "Gå i seng",
  "go_to_market": "Gå til markedet",
  "go_to_party": "Gå til fest",
  "go_to_pool": "Gå til svømmehallen",
  "go_to_school": "Gå i skole",
  "go_to_shop": "Gå i butikken",
  "go_to_sleep": "Fald i søvn",
  "going_shopping": "Handle ind",
  "going_to_bed": "Gå i seng",
  "going_to_school": "Gå i skole",
  "goldfish": "Guldfisk",
  "grab_umbrella": "Tag paraplyen",
  "graduation": "Dimission",
  "grapes": "Vindruer",
  "green": "Grøn",
  "green_apple": "Grønt æble",
  "grind_into_flour": "Mal til mel",
  "guide_dog": "Førerhund",
  "guitar": "Guitar",
  "gym_class": "Gymnastiktime",
  "hair": "Hår",
  "hairdresser": "Frisør",
  "halloween": "Halloween",
  "hammer": "Hammer",
  "hamster": "Hamster",
  "hand": "Hånd",
  "hand_sanitiser": "Håndsprit",
  "handbag": "Håndtaske",
  "hang_it_on_the_wall": "Hæng det på væggen",
  "hang_out_to_dry": "Hæng op til tørre",
  "harbour": "Havn",
  "hard_things": "Hårde ting",
  "harvest_wheat": "Høst hvede",
  "has_wheels": "Har hjul",
  "has_wings": "Har vinger",
  "hat": "Hat",
  "hats": "Hatte",
  "have_a_chat": "Snak lidt",
  "have_a_shower": "Tag et brusebad",
  "have_a_warm_drink": "Drik noget varmt",
  "have_a_wash": "Tag en vask",
  "have_breakfast": "Spis morgenmad",
  "have_lessons": "Hav undervisning",
  "have_morning_tea": "Drik morgenthe",
  "hawaii": "Hawaii",
  "head_out_prepared": "Gå forberedt ud",
  "headwear": "Hovedbeklædning",
  "hear_birds": "Hør fuglene",
  "hear_the_news": "Hør nyheder",
  "hedgehog": "Pindsvin",
  "helicopter": "Helikopter",
  "hen_sits_on_egg": "Hønen ruger på ægget",
  "herb": "Urt",
  "herbal_tea": "Urtete",
  "hibiscus": "Hibiscus",
  "hold_it_out": "Hold det frem",
  "holiday": "Ferie",
  "holiday_abroad": "Ferie i udlandet",
  "home": "Hjem",
  "honey": "Honning",
  "hoop": "Ring",
  "horse": "Hest",
  "hospital": "Hospital",
  "hot_chocolate": "Varm kakao",
  "hot_drinks": "Varme drikke",
  "hot_tea": "Varm te",
  "hot_things": "Varme ting",
  "house": "Hus",
  "hurry_home": "Skynd dig hjem",
  "ice": "Is",
  "ice_cream": "Is",
  "ice_cube": "Isterning",
  "ice_rink": "Skøjtebane",
  "iced_drink": "Isdrik",
  "iced_water": "Isvand",
  "iceland": "Island",
  "in_winter": "Om vinteren",
  "indoor_clothes": "Indendørs tøj",
  "insects": "Insekter",
  "instruments": "Instrumenter",
  "iron": "Strygejern",
  "it_gets_delivered": "Det bliver leveret",
  "it_is_a_book": "Det er en bog",
  "it_starts_raining": "Det begynder at regne",
  "italian_food": "Italiensk mad",
  "italy": "Italien",
  "japan": "Japan",
  "jewellery": "Smykker",
  "jug": "Kande",
  "juice": "Juice",
  "juice_box": "Juiceboks",
  "jump_in_the_pool": "Hop i poolen",
  "jungle": "Jungle",
  "key": "Nøgle",
  "king": "Konge",
  "kitchen": "Køkken",
  "kitchen_cleaning": "Køkkenrengøring",
  "kitchen_items": "Køkkenting",
  "knife": "Kniv",
  "knitting": "Strikning",
  "knitting_needles": "Strikkepinde",
  "ladder": "Stige",
  "ladybird": "Mariehøne",
  "land": "Land",
  "land_animals": "Landdyr",
  "land_vehicles": "Landkøretøjer",
  "laptop": "Bærbar computer",
  "laundry": "Vasketøj",
  "lead": "Snor",
  "leaf": "Blad",
  "leave_them_to_dry": "Lad dem tørre",
  "leaves": "Blade",
  "lemon": "Citron",
  "lemonade": "Lemonade",
  "letter": "Brev",
  "letterbox": "Postkasse",
  "lettuce": "Salat",
  "library": "Bibliotek",
  "light_bulb": "Pære",
  "light_candles": "Tænd lys",
  "light_the_fire": "Tænd ilden",
  "lion": "Løve",
  "lizard": "Firben",
  "load_the_van": "Læs varevognen",
  "lobster": "Hummer",
  "lock": "Lås",
  "log": "Brænde",
  "lollipop": "Slikkepind",
  "london": "London",
  "look_in_mirror": "Se i spejlet",
  "lunch": "Frokost",
  "lunchtime": "Frokosttid",
  "magnet": "Magnet",
  "make_a_list": "Skriv en liste",
  "make_coffee": "Lav kaffe",
  "make_jam": "Lav syltetøj",
  "make_pie": "Lav tærte",
  "make_popcorn": "Lav popcorn",
  "make_scrambled_eggs": "Lav røræg",
  "make_soup": "Lav suppe",
  "make_tea": "Lav te",
  "make_the_bed": "Red sengen",
  "make_the_bed_fresh": "Skift sengetøj",
  "making_bread": "Bage brød",
  "making_dinner": "Lave aftensmad",
  "making_honey": "Lave honning",
  "making_tea": "Lave te",
  "mango": "Mango",
  "map": "Kort",
  "mashed_banana": "Most banan",
  "masks": "Masker",
  "match": "Tændstik",
  "meat": "Kød",
  "melon": "Melon",
  "melt_it": "Smelt det",
  "metal": "Metal",
  "microphone": "Mikrofon",
  "microscope": "Mikroskop",
  "milk": "Mælk",
  "milkshake": "Milkshake",
  "mix_ingredients": "Bland ingredienserne",
  "mix_the_dough": "Ælt dejen",
  "moon": "Måne",
  "mop_the_floor": "Vask gulvet",
  "morning": "Morgen",
  "morning_comes": "Morgenen kommer",
  "motorbike": "Motorcykel",
  "mountain": "Bjerg",
  "mountains": "Bjerge",
  "movie_night": "Filmaften",
  "mug": "Krus",
  "mushroom": "Svamp",
  "music": "Musik",
  "music_plays": "Musikken spiller",
  "music_starts": "Musikken starter",
  "musical_instruments": "Musikinstrumenter",
  "nail": "Søm",
  "necklace": "Halskæde",
  "needle": "Nål",
  "new_york": "New York",
  "newspaper": "Avis",
  "nice_weather": "Dejligt vejr",
  "night": "Nat",
  "night_cream": "Natcreme",
  "night_time": "Nattetid",
  "notepad": "Notesblok",
  "oak_tree": "Egetræ",
  "ocean": "Hav",
  "ocean_animals": "Havdyr",
  "octopus": "Blæksprutte",
  "office": "Kontor",
  "office_desk": "Skrivebord",
  "office_items": "Kontorartikler",
  "old_key": "Gammel nøgle",
  "onion": "Løg",
  "open_book": "Åbn bogen",
  "open_door": "Åbn døren",
  "open_presents": "Åbn gaver",
  "open_the_door": "Åbn døren",
  "open_the_window": "Åbn vinduet",
  "orange": "Appelsin",
  "orange_juice": "Appelsinjuice",
  "orchestra": "Orkester",
  "order_pizza": "Bestil pizza",
  "outdoor_clothes": "Udendørs tøj",
  "owl": "Ugle",
  "pack_a_picnic": "Pak en picnickurv",
  "pack_boxes": "Pak kasser",
  "pack_suitcase": "Pak kufferten",
  "paint": "Maling",
  "paint_a_picture": "Mal et billede",
  "paint_palette": "Malerpalette",
  "paint_the_sky": "Mal himlen",
  "paintbrush": "Pensel",
  "painting": "Maleri",
  "palm_tree": "Palme",
  "pancakes": "Pandekager",
  "paper": "Papir",
  "paper_clip": "Papirclips",
  "paperclip": "Papirclips",
  "paris": "Paris",
  "park_walk": "Gåtur i parken",
  "parrot": "Papegøje",
  "party": "Fest",
  "party_food": "Festmad",
  "party_poppers": "Bordbomber",
  "pasta": "Pasta",
  "pay_at_till": "Betal i kassen",
  "peach": "Fersken",
  "pear": "Pære",
  "peel_and_chop": "Skræl og hak",
  "peel_carrots": "Skræl gulerødder",
  "pen": "Kuglepen",
  "pencil": "Blyant",
  "penguin": "Pingvin",
  "pepper": "Peber",
  "petrol_pump": "Benzinstander",
  "pets": "Kæledyr",
  "pharmacy": "Apotek",
  "phone": "Telefon",
  "phone_rings": "Telefonen ringer",
  "photo": "Foto",
  "piano": "Klaver",
  "pick_apples": "Pluk æbler",
  "pick_herbs": "Pluk urter",
  "pick_strawberries": "Pluk jordbær",
  "pick_up_basket": "Tag kurven",
  "pick_up_brush": "Tag børsten",
  "pick_up_fork": "Tag gaflen",
  "picnic": "Picnic",
  "picture_book": "Billedbog",
  "picture_frame": "Billedramme",
  "pie": "Tærte",
  "pig": "Gris",
  "pillow": "Pude",
  "pilot": "Pilot",
  "pine_forest": "Fyrreskov",
  "pine_tree": "Fyrretræ",
  "pineapple": "Ananas",
  "pizza": "Pizza",
  "pizzeria": "Pizzeria",
  "plane": "Fly",
  "plant": "Plante",
  "plant_a_tree": "Plant et træ",
  "plant_bulbs": "Plant løg",
  "plant_pot": "Urtepotte",
  "plant_the_seed": "Plant frøet",
  "plants": "Planter",
  "plaster": "Plaster",
  "plate": "Tallerken",
  "play": "Leg",
  "play_a_game": "Spil et spil",
  "play_guitar": "Spil guitar",
  "play_music": "Spil musik",
  "play_outside": "Leg udenfor",
  "playing_piano": "Spille klaver",
  "playtime": "Legetid",
  "police_car": "Politibil",
  "police_station": "Politistation",
  "poodle": "Puddel",
  "pool": "Svømmebassin",
  "pop_star": "Popstjerne",
  "post_it": "Send det",
  "post_office": "Posthus",
  "postbox": "Postkasse",
  "postman": "Postbud",
  "pot": "Gryde",
  "potato": "Kartoffel",
  "potatoes": "Kartofler",
  "potted_plant": "Potteplante",
  "pour_batter": "Hæld dejen",
  "pour_cereal": "Hæld morgenmad op",
  "pour_hot_water": "Hæld varmt vand",
  "pour_milk": "Hæld mælk",
  "prawn": "Reje",
  "press_send": "Tryk send",
  "pretzel": "Kringle",
  "print_them": "Print dem",
  "printer": "Printer",
  "protractor": "Vinkelmåler",
  "pudding": "Dessert",
  "puddles_appear": "Vandpytter dukker op",
  "pumpkin": "Græskar",
  "pumpkins": "Græskar",
  "put_dishes_in": "Sæt tallerkener i",
  "put_in_envelope": "Læg i kuvert",
  "put_in_machine": "Sæt i maskinen",
  "put_in_oven": "Sæt i ovnen",
  "put_in_pot": "Kom i gryden",
  "put_on_boots": "Tag støvler på",
  "put_on_gloves": "Tag handsker på",
  "put_on_plate": "Læg på tallerkenen",
  "put_on_pyjamas": "Tag pyjamas på",
  "put_on_shoes": "Tag sko på",
  "put_on_smart_clothes": "Tag pænt tøj på",
  "put_photos_in_album": "Sæt fotos i albummet",
  "put_up_tree": "Sæt juletræet op",
  "pyjamas": "Pyjamas",
  "quiet_evening": "Stille aften",
  "rabbit": "Kanin",
  "radio": "Radio",
  "rain": "Regn",
  "rain_forecast": "Regnvejr i udsigten",
  "rain_starts": "Regnen starter",
  "rain_stops": "Regnen stopper",
  "rainbow": "Regnbue",
  "rainy_day": "Regnvejrsdag",
  "rainy_day_things": "Regnvejrsting",
  "rattle": "Rangle",
  "razor": "Barbermaskine",
  "read_a_book": "Læs en bog",
  "read_a_story": "Læs en historie",
  "read_more": "Læs mere",
  "read_pages": "Læs sider",
  "read_recipe": "Læs opskriften",
  "read_the_paper": "Læs avisen",
  "reading": "Læsning",
  "receive_a_gift": "Modtag en gave",
  "red": "Rød",
  "reel_in_the_fish": "Hiv fisken ind",
  "remote": "Fjernbetjening",
  "reptiles": "Krybdyr",
  "restaurant": "Restaurant",
  "ring": "Ring",
  "rinse_off": "Skyl af",
  "risotto": "Risotto",
  "roast_chicken": "Stegt kylling",
  "roast_meat": "Steg kød",
  "rock": "Sten",
  "rocket": "Raket",
  "rod": "Stang",
  "roof": "Tag",
  "room_is_clean": "Værelset er rent",
  "rooster": "Hane",
  "rooster_crows": "Hanen galer",
  "rose": "Rose",
  "round_things": "Runde ting",
  "rowing_boat": "Robåd",
  "rubbish": "Affald",
  "rugby_ball": "Rugbybold",
  "ruler": "Lineal",
  "run_a_bath": "Fylde badekarret",
  "sailboat": "Sejlbåd",
  "salad": "Salat",
  "sandals": "Sandaler",
  "sandcastle": "Sandslot",
  "sandwiches": "Sandwiches",
  "saucer": "Underkop",
  "saw": "Sav",
  "say_goodbye": "Sig farvel",
  "scarf": "Tørklæde",
  "school": "Skole",
  "school_day": "Skoledag",
  "school_trip": "Skoleudflugt",
  "scissors": "Saks",
  "scooter": "Løbehjul",
  "scratching_post": "Kradsetræ",
  "screwdriver": "Skruetrækker",
  "scrub_them_clean": "Skrub dem rene",
  "sea_creatures": "Havdyr",
  "seafood": "Skaldyr",
  "seal": "Sæl",
  "seashell": "Muslingeskal",
  "seasons": "Årstider",
  "see_a_rainbow": "Se en regnbue",
  "see_blossom": "Se blomstringen",
  "see_the_moon": "Se månen",
  "seed": "Frø",
  "seedling": "Spire",
  "serve_and_eat": "Server og spis",
  "serve_on_plate": "Server på tallerkenen",
  "serve_pasta_sauce": "Server pastasauce",
  "serve_the_meal": "Server måltidet",
  "sewing_kit": "Sykit",
  "shampoo": "Shampoo",
  "shape_the_dough": "Form dejen",
  "shapes": "Former",
  "shark": "Haj",
  "sheep": "Får",
  "ship": "Skib",
  "shoe": "Sko",
  "shoes": "Sko",
  "shop": "Butik",
  "shopping": "Indkøb",
  "shopping_trolley": "Indkøbsvogn",
  "shorts": "Shorts",
  "show_ticket": "Vis billet",
  "shower": "Bruser",
  "sing_a_song": "Syng en sang",
  "sing_along": "Syng med",
  "sing_happy_birthday": "Syng fødselsdagssang",
  "singer": "Sanger",
  "singing": "Sang",
  "sit_and_read": "Sid og læs",
  "sit_back_and_enjoy": "Læn dig tilbage og nyd det",
  "sit_by_the_fire": "Sid ved ilden",
  "sit_down_and_enjoy": "Sid ned og nyd det",
  "sit_in_chair": "Sid i stolen",
  "ski_resort": "Skisportssted",
  "skiing": "Skisport",
  "skis": "Ski",
  "sleeping": "Sover",
  "slippers": "Hjemmesko",
  "smile": "Smil",
  "snail": "Snegl",
  "snake": "Slange",
  "snow": "Sne",
  "snow_falls": "Sneen falder",
  "snowflake": "Snefnug",
  "snowman": "Snemand",
  "soap": "Sæbe",
  "social_evening": "Hyggelig aften",
  "sock": "Sok",
  "socks": "Sokker",
  "sofa": "Sofa",
  "soft_things": "Bløde ting",
  "solo_singer": "Solosanger",
  "solve_the_puzzle": "Løs puslespillet",
  "soup": "Suppe",
  "space": "Rummet",
  "space_things": "Rumting",
  "spade": "Spade",
  "spain": "Spanien",
  "spanner": "Skruenøgle",
  "sponge": "Svamp",
  "spoon": "Ske",
  "sports": "Sport",
  "sports_day": "Sportsdag",
  "spring": "Forår",
  "sprout": "Spire",
  "square": "Firkant",
  "square_things": "Firkantede ting",
  "squeeze_lemon": "Pres citronen",
  "squirrel": "Egern",
  "stadium": "Stadion",
  "stand_on_stage": "Stå på scenen",
  "star": "Stjerne",
  "stars": "Stjerner",
  "start_cooking": "Begynd at lave mad",
  "start_knitting": "Begynd at strikke",
  "start_reading": "Begynd at læse",
  "start_sewing": "Begynd at sy",
  "start_singing": "Begynd at synge",
  "start_the_car": "Start bilen",
  "stationery": "Kontorartikler",
  "steak": "Bøf",
  "step_inside": "Træd indenfor",
  "stethoscope": "Stetoskop",
  "stew": "Gryderet",
  "stew_is_ready": "Gryderetten er klar",
  "stir_and_drink": "Rør og drik",
  "storm": "Storm",
  "strawberry": "Jordbær",
  "streamers": "Serpentiner",
  "strip_the_bed": "Tag sengetøjet af",
  "suitcase": "Kuffert",
  "summer": "Sommer",
  "summer_holiday": "Sommerferie",
  "sun": "Sol",
  "sun_comes_out": "Solen kommer frem",
  "sun_cream": "Solcreme",
  "sun_hat": "Solhat",
  "sun_is_rising": "Solen står op",
  "sunbathe": "Solbade",
  "sunflower": "Solsikke",
  "sunglasses": "Solbriller",
  "sunlight": "Sollys",
  "sunny_day": "Solskinsdag",
  "sunshine": "Solskin",
  "supermarket": "Supermarked",
  "surfing": "Surfing",
  "sushi": "Sushi",
  "sweep_floor": "Fej gulvet",
  "sweep_the_floor": "Fej gulvet",
  "sweet": "Slik",
  "sweets": "Slik",
  "swimming": "Svømning",
  "swimsuit": "Badedragt",
  "t_shirt": "T-shirt",
  "table": "Bord",
  "tablets": "Tabletter",
  "take_it_home": "Tag det med hjem",
  "take_photos": "Tag fotos",
  "take_shopping_home": "Tag indkøbene med hjem",
  "take_them_home": "Tag dem med hjem",
  "talking": "Snak",
  "tape_measure": "Målebånd",
  "target": "Mål",
  "taxi": "Taxa",
  "tea": "Te",
  "tea_bags": "Teposer",
  "tea_towel": "Viskestykke",
  "teacher": "Lærer",
  "teacup": "Tekop",
  "teapot": "Tekande",
  "tears": "Tårer",
  "teddy_bear": "Bamse",
  "teenager": "Teenager",
  "teeth": "Tænder",
  "television": "Fjernsyn",
  "tennis": "Tennis",
  "tennis_ball": "Tennisbold",
  "tent": "Telt",
  "test_tube": "Reagensglas",
  "theatre": "Teater",
  "theatre_masks": "Teatermasker",
  "thermometer": "Termometer",
  "thick_socks": "Tykke sokker",
  "things_in_the_sky": "Ting på himlen",
  "things_that_fly": "Ting der flyver",
  "things_that_swim": "Ting der svømmer",
  "thread": "Tråd",
  "thread_needle": "Trå nålen",
  "tide_goes_out": "Tidevandet går ud",
  "tie_a_ribbon": "Bind et bånd",
  "tiger": "Tiger",
  "timepieces": "Ure",
  "tin_of_beans": "Dåse bønner",
  "toast": "Toast",
  "tomato": "Tomat",
  "tools": "Værktøj",
  "toothbrush": "Tandbørste",
  "toothpaste": "Tandpasta",
  "top_hat": "Høj hat",
  "torch": "Lommelygte",
  "tornado": "Tornado",
  "train": "Tog",
  "train_station": "Togstation",
  "trainer": "Løbesko",
  "transport": "Transport",
  "tree": "Træ",
  "tree_freezes": "Træet fryser",
  "tree_grows_tall": "Træet vokser sig højt",
  "trees": "Træer",
  "trophy": "Pokal",
  "tropical_fish": "Tropisk fisk",
  "tropical_fruits": "Tropiske frugter",
  "tropical_things": "Tropiske ting",
  "trumpet": "Trompet",
  "try_it_on": "Prøv det",
  "tulip": "Tulipan",
  "turn_on_light": "Tænd lyset",
  "turn_on_radio": "Tænd radioen",
  "turn_on_tv": "Tænd fjernsynet",
  "turtle": "Skildpadde",
  "umbrella": "Paraply",
  "unpack_boxes": "Pak kasserne ud",
  "unwrap_it": "Pak det op",
  "vegetable_patch": "Køkkenhave",
  "vegetables": "Grøntsager",
  "vehicles": "Køretøjer",
  "violin": "Violin",
  "vitamins": "Vitaminer",
  "volcano": "Vulkan",
  "wait_patiently": "Vent tålmodigt",
  "wake_up": "Vågn op",
  "walk_on_sand": "Gå på sandet",
  "walk_outside": "Gå udenfor",
  "walk_the_dog": "Gå tur med hunden",
  "walkies": "Gåtur",
  "warm_coat": "Varm frakke",
  "wash_clothes": "Vask tøj",
  "wash_sheets": "Vask lagner",
  "wash_the_car": "Vask bilen",
  "wash_the_dog": "Vask hunden",
  "wash_with_soap": "Vask med sæbe",
  "washing_machine": "Vaskemaskine",
  "washing_up_liquid": "Opvaskemiddel",
  "watch": "Armbåndsur",
  "watch_a_film": "Se en film",
  "watch_it_grow": "Se den vokse",
  "watch_tv": "Se fjernsyn",
  "water": "Vand",
  "water_it": "Vand den",
  "water_them": "Vand dem",
  "water_vehicles": "Fartøjer",
  "watering_can": "Vandkande",
  "watermelon": "Vandmelon",
  "waves": "Bølger",
  "weather": "Vejr",
  "wedding": "Bryllup",
  "wellington_boots": "Gummistøvler",
  "wet_the_brush": "Fugt penslen",
  "whale": "Hval",
  "wheat": "Hvede",
  "whisk_together": "Pisk sammen",
  "wild_animals": "Vilde dyr",
  "wild_west": "Det vilde vesten",
  "willow": "Pil",
  "wind": "Vind",
  "window": "Vindue",
  "windy_days": "Blæsende dage",
  "winner": "Vinder",
  "winter": "Vinter",
  "winter_clothing": "Vintertøj",
  "winter_holiday": "Vinterferie",
  "wipe_surfaces": "Tør overflader af",
  "wood": "Træ",
  "woodland_animals": "Skovdyr",
  "wool": "Uld",
  "woolly_hat": "Ulden hue",
  "work": "Arbejde",
  "worm": "Orm",
  "wrap_it_up": "Pak det ind",
  "wrap_presents": "Pak gaver ind",
  "wrap_the_gift": "Pak gaven ind",
  "wrap_them": "Pak dem ind",
  "wrap_up_warm": "Klæd dig varmt på",
  "wrench": "Skruenøgle",
  "write_a_letter": "Skriv et brev",
  "write_an_email": "Skriv en e-mail",
  "writing_a_book": "Skrive en bog",
  "writing_tools": "Skriveredskaber",
  "zoo": "Zoo",
  // True/false statements, facts, and historical descriptions
  "9_plus_1_equals_10": "9 plus 1 er lig med 10.",
  "a_bicycle_has_2_wheels_bi_means_two": "En cykel har 2 hjul — \"bi\" betyder to.",
  "a_bicycle_has_3_wheels": "En cykel har 3 hjul.",
  "a_butterfly_begins_as_a_tiny_egg_then_a_caterpillar_then_a_chrysalis": "En sommerfugl begynder som et lille æg, derefter en larve og så en puppe.",
  "a_caterpillar_turns_into_a_butterfly": "En larve bliver til en sommerfugl.",
  "a_clock_has_12_hours_on_its_face": "Et ur har 12 timer på urskiven.",
  "a_dozen_always_means_twelve_of_something": "Et dusin betyder altid tolv af noget.",
  "a_dozen_means_12": "Et dusin er 12.",
  "a_football_pitch_is_rectangular": "En fodboldbane er rektangulær.",
  "a_guitar_has_strings": "En guitar har strenge.",
  "a_piano_has_black_and_white_keys": "Et klaver har sorte og hvide tangenter.",
  "a_postbox_in_britain_is_red": "En postkasse i Storbritannien er rød.",
  "a_rainbow_has_7_colours": "En regnbue har 7 farver.",
  "a_spider_is_an_insect": "En edderkop er et insekt.",
  "a_square_has_4_equal_sides": "En firkant har 4 lige sider.",
  "a_square_has_5_sides": "En firkant har 5 sider.",
  "a_standard_clock_face_shows_numbers_1_through_12": "En almindelig urskive viser tallene 1 til 12.",
  "a_standard_piano_has_both_black_and_white_keys": "Et almindeligt klaver har både sorte og hvide tangenter.",
  "a_triangle_has_3_sides_tri_means_three": "En trekant har 3 sider — \"tri\" betyder tre.",
  "a_triangle_has_4_sides": "En trekant har 4 sider.",
  "a_violin_is_a_musical_instrument": "En violin er et musikinstrument.",
  "a_wagging_tail_usually_means_a_dog_is_feeling_happy_or_excited": "En logrende hale betyder som regel, at hunden er glad eller begejstret.",
  "a_week_has_7_days_from_monday_to_sunday": "En uge har 7 dage, fra mandag til søndag.",
  "a_year_has_12_months": "Et år har 12 måneder.",
  "african_elephants_are_the_biggest_animals_on_land": "Afrikanske elefanter er de største dyr på land.",
  "alexander_fleming_discovered_penicillin_one_of_the_most_important_medical_breakthroughs_ever": "Alexander Fleming opdagede penicillin, et af de vigtigste medicinske gennembrud nogensinde.",
  "alexander_graham_bell_made_the_first_successful_telephone_call_mr_watson_come_here": "Alexander Graham Bell foretog det første vellykkede telefonopkald: \"Hr. Watson, kom herhen.\"",
  "all_birds_lay_eggs_to_have_their_young": "Alle fugle lægger æg for at få deres unger.",
  "an_hour_has_60_minutes": "En time har 60 minutter.",
  "an_octopus_has_8_arms": "En blæksprutte har 8 arme.",
  "apollo_8_astronauts_orbited_the_moon_and_took_the_famous_earthrise_photograph": "Apollo 8-astronauterne kredsede om Månen og tog det berømte \"Earthrise\"-fotografi.",
  "apple_trees_produce_fruit_every_autumn": "Æbletræer giver frugt hvert efterår.",
  "apples_grow_on_trees": "Æbler vokser på træer.",
  "archaeologists_have_found_3_000_year_old_honey_that_was_still_edible": "Arkæologer har fundet 3.000 år gammel honning, der stadig var spiselig!",
  "arm": "ARM",
  "armistice_day_world_war_i_ended_at_the_11th_hour_of_the_11th_day_of_the_11th_month": "Våbenstilstandsdagen — Første Verdenskrig sluttede den 11. time den 11. dag i den 11. måned.",
  "as_chlorophyll_fades_in_autumn_leaves_turn_beautiful_warm_colours": "Når klorofyllet falmer om efteråret, skifter bladene til smukke, varme farver.",
  "ash": "ASK",
  "aunt": "TANTE",
  "australia_is_a_country_and_a_continent": "Australien er et land og et kontinent.",
  "australia_is_the_only_place_that_is_both_a_country_and_a_continent": "Australien er det eneste sted, der er både et land og et kontinent.",
  "autumn_leaves_often_turn_orange_and_red": "Efterårsblade bliver ofte orange og røde.",
  "banana_plants_look_like_trees_but_are_actually_giant_herbs": "Bananplanter ligner træer, men er faktisk kæmpeurter!",
  "bananas_are_blue": "Bananer er blå.",
  "bananas_are_yellow_when_ripe": "Bananer er gule, når de er modne.",
  "bananas_grow_on_trees": "Bananer vokser på træer.",
  "barking_is_how_dogs_communicate": "Gøen er hundes måde at kommunikere på.",
  "bats_are_blind": "Flagermus er blinde.",
  "bats_can_actually_see_they_also_use_echolocation_to_navigate": "Flagermus kan faktisk se — de bruger også ekkolokalisering til at navigere.",
  "beat": "SLÅ",
  "bees_collect_nectar_from_flowers_and_turn_it_into_honey": "Bier samler nektar fra blomster og laver det om til honning.",
  "bees_make_honey": "Bier laver honning.",
  "big_ben_is_in_london": "Big Ben er i London.",
  "big_ben_is_the_famous_bell_inside_the_elizabeth_tower_at_the_houses_of_parliament": "Big Ben er den berømte klokke inde i Elizabeth-tårnet ved parlamentsbygningen.",
  "birds_lay_eggs": "Fugle lægger æg.",
  "bowl": "SKÅL",
  "bread_is_baked_in_an_oven": "Brød bages i en ovn.",
  "breakfast_is_the_first_meal_of_the_day": "Morgenmad er dagens første måltid.",
  "britain_declared_war_on_germany_families_gathered_around_their_radios_to_hear_the_announcement": "Storbritannien erklærede Tyskland krig. Familier samledes om deres radioer for at høre meddelelsen.",
  "britain_switched_to_decimal_currency_goodbye_to_shillings_and_half_crowns": "Storbritannien skiftede til decimalmønt — farvel til shilling og halvkroner!",
  "buckingham_palace_in_london_is_the_official_royal_residence": "Buckingham Palace i London er den officielle kongelige residens.",
  "butterflies_start_life_as_caterpillars": "Sommerfugle begynder livet som larver.",
  "camel_humps_actually_store_fat_not_water": "Kamelpukler lagrer faktisk fedt, ikke vand.",
  "camels_store_water_in_their_humps": "Kameler lagrer vand i deres pukler.",
  "carrots_are_a_type_of_meat": "Gulerødder er en type kød.",
  "carrots_are_good_for_your_eyesight": "Gulerødder er gode for synet.",
  "carrots_are_vegetables_that_grow_in_the_ground": "Gulerødder er grøntsager, der vokser i jorden.",
  "carrots_contain_vitamin_a_which_helps_keep_your_eyes_healthy": "Gulerødder indeholder A-vitamin, som hjælper med at holde øjnene sunde.",
  "caterpillars_go_through_metamorphosis_to_become_butterflies": "Larver gennemgår forvandling for at blive sommerfugle.",
  "cats_can_fly": "Katte kan flyve.",
  "cats_cannot_fly_but_they_are_great_climbers": "Katte kan ikke flyve — men de er fantastiske klatrere!",
  "chickens_lay_eggs": "Høns lægger æg.",
  "chocolate_is_made_from_cocoa_beans": "Chokolade er lavet af kakaobønner.",
  "christmas_day_is_on_the_25th_of_december": "Juledag er den 25. december.",
  "christmas_is_celebrated_on_december_25th_each_year": "Jul fejres den 25. december hvert år.",
  "cocoa_beans_are_the_main_ingredient_in_chocolate": "Kakaobønner er hovedingrediensen i chokolade.",
  "concorde_made_its_final_commercial_flight_ending_the_era_of_supersonic_passenger_travel": "Concorde fløj sin sidste kommercielle flyvning og afsluttede æraen for supersonisk passagerrejser.",
  "cows_are_too_heavy_to_climb_trees": "Køer er for tunge til at klatre i træer!",
  "cows_can_climb_trees": "Køer kan klatre i træer.",
  "crocodiles_are_carnivores_they_eat_meat": "Krokodiller er kødædere — de spiser kød.",
  "crocodiles_are_herbivores": "Krokodiller er planteædere.",
  "d_day_allied_forces_landed_on_the_beaches_of_normandy_a_turning_point_in_the_war": "D-dag — Allierede styrker landede på Normandiets strande, et vendepunkt i krigen.",
  "dad": "FAR",
  "december_comes_before_november": "December kommer før november.",
  "diamonds_are_soft": "Diamanter er bløde.",
  "diamonds_are_the_hardest_natural_material_on_earth": "Diamanter er det hårdeste naturlige materiale på Jorden.",
  "dig": "GRAV",
  "dogs_can_bark": "Hunde kan gø.",
  "dogs_wag_their_tails_when_happy": "Hunde logrer med halen, når de er glade.",
  "dolphins_are_found_in_oceans_and_seas_around_the_world": "Delfiner findes i have og oceaner rundt om i verden.",
  "dolphins_live_in_the_ocean": "Delfiner lever i havet.",
  "door": "DØR",
  "dough_is_shaped_and_baked_in_an_oven_to_make_bread": "Dej formes og bages i en ovn for at lave brød.",
  "dove": "DUE",
  "ear": "ØRE",
  "edmund_hillary_and_tenzing_norgay_reached_the_summit_of_mount_everest": "Edmund Hillary og Tenzing Norgay nåede toppen af Mount Everest.",
  "elephants_are_much_much_bigger_than_mice": "Elefanter er meget, meget større end mus!",
  "elephants_are_smaller_than_mice": "Elefanter er mindre end mus.",
  "elephants_are_the_largest_land_animals": "Elefanter er de største landdyr.",
  "elm": "ELM",
  "england": "England",
  "england_beat_west_germany_4_2_to_win_the_world_cup_at_wembley_stadium": "England slog Vesttyskland 4-2 og vandt VM på Wembley Stadium.",
  "england_won_the_rugby_world_cup_in_a_dramatic_final_against_australia": "England vandt rugby-VM i en dramatisk finale mod Australien.",
  "fig": "FIGEN",
  "fish_breathe_through_gills_and_live_in_water": "Fisk ånder gennem gæller og lever i vand.",
  "fish_live_in_water": "Fisk lever i vand.",
  "fog": "TÅGE",
  "football_pitches_are_always_rectangular_in_shape": "Fodboldbaner er altid rektangulære.",
  "fork": "GAFFEL",
  "frogs_are_amphibians_they_live_in_water_and_on_land": "Frøer er padder — de lever i vand og på land.",
  "frogs_are_mammals": "Frøer er pattedyr.",
  "galloping_is_the_fastest_way_a_horse_can_run": "Galop er den hurtigste gangart for en hest.",
  "gertrude_ederle_became_the_first_woman_to_swim_across_the_english_channel": "Gertrude Ederle blev den første kvinde, der svømmede over Den Engelske Kanal.",
  "giraffes_are_short_animals": "Giraffer er korte dyr.",
  "giraffes_are_the_tallest_animals_on_earth": "Giraffer er de højeste dyr på Jorden!",
  "goal": "MÅL",
  "goldfish_can_actually_remember_things_for_months": "Guldfisk kan faktisk huske ting i flere måneder!",
  "goldfish_have_a_memory_of_only_3_seconds": "Guldfisk har kun en hukommelse på 3 sekunder.",
  "guglielmo_marconi_received_the_first_transatlantic_radio_signal_connecting_continents": "Guglielmo Marconi modtog det første transatlantiske radiosignal og forbandt kontinenterne.",
  "hen": "HØNE",
  "hens_lay_eggs_which_is_where_our_breakfast_eggs_come_from": "Høner lægger æg, og det er derfra, vores morgenæg kommer.",
  "hill": "BAKKE",
  "honey_never_goes_bad": "Honning bliver aldrig dårligt.",
  "horses_can_gallop": "Heste kan galoppere.",
  "humans_have_2_arms": "Mennesker har 2 arme.",
  "humans_have_3_arms": "Mennesker har 3 arme.",
  "ice_cream_is_served_cold": "Is serveres koldt.",
  "ice_cream_melts_if_it_gets_warm_so_it_is_always_cold": "Is smelter, hvis den bliver varm, så den er altid kold.",
  "ice_is_frozen_water": "Is er frosset vand.",
  "if_you_look_at_italy_on_a_map_it_really_does_look_like_a_boot": "Hvis du kigger på Italien på et kort, ligner det virkelig en støvle!",
  "in_summer_the_sun_is_higher_and_days_are_longer_making_it_warmer": "Om sommeren står solen højere, og dagene er længere, hvilket gør det varmere.",
  "iris": "IRIS",
  "italy_is_shaped_like_a_boot": "Italien har form som en støvle.",
  "john_logie_baird_gave_the_first_public_demonstration_of_television": "John Logie Baird gav den første offentlige demonstration af fjernsyn.",
  "kick": "SPARK",
  "king_edward_viii_abdicated_the_throne_for_love_and_his_brother_became_king_george_vi": "Kong Edward VIII abdicerede tronen af kærlighed, og hans bror blev Kong George VI.",
  "koalas_are_bears": "Koalaer er bjørne.",
  "koalas_are_marsupials_not_bears_despite_being_called_koala_bears": "Koalaer er pungdyr, ikke bjørne, på trods af at de kaldes \"koalabjørne\".",
  "lake": "SØ",
  "lamp": "LAMPE",
  "leg": "BEN",
  "lemons_are_sour_because_they_contain_citric_acid": "Citroner er sure, fordi de indeholder citronsyre.",
  "lemons_are_sweet": "Citroner er søde.",
  "lily": "LILJE",
  "lime": "LIME",
  "live_aid_concert_raised_millions_for_famine_relief_a_moment_of_global_unity_through_music": "Live Aid-koncerten indsamlede millioner til sulthjælp — et øjeblik af global sammenhold gennem musik.",
  "london_has_been_england": "London har været Englands",
  "london_is_the_capital_of_england": "London er hovedstaden i England.",
  "mahatma_gandhi_began_the_famous_salt_march_a_peaceful_protest_that_inspired_millions": "Mahatma Gandhi begyndte den berømte saltmarch, en fredelig protest, der inspirerede millioner.",
  "mars_is_the_closest_planet_to_the_sun": "Mars er den nærmeste planet til Solen.",
  "martin_luther_king_jr_delivered_his_i_have_a_dream_speech_in_washington_dc": "Martin Luther King Jr. holdt sin \"I Have a Dream\"-tale i Washington DC.",
  "mercury_is_the_closest_planet_to_the_sun_not_mars": "Merkur er den nærmeste planet til Solen, ikke Mars.",
  "milk_comes_from_cows": "Mælk kommer fra køer.",
  "most_guitars_have_6_strings": "De fleste guitarer har 6 strenge.",
  "most_of_the_milk_we_drink_comes_from_dairy_cows": "Det meste af den mælk, vi drikker, kommer fra malkekøer.",
  "most_owls_are_nocturnal_active_at_night_and_sleeping_by_day": "De fleste ugler er nataktive — aktive om natten og sover om dagen.",
  "most_penguins_live_in_the_southern_hemisphere_near_the_south_pole": "De fleste pingviner lever på den sydlige halvkugle, nær Sydpolen.",
  "most_tomatoes_are_red_though_some_varieties_can_be_yellow_or_green": "De fleste tomater er røde, selvom nogle sorter kan være gule eller grønne.",
  "mud": "MUDDER",
  "mum": "MOR",
  "nasa": "NASA",
  "neil_armstrong_became_the_first_person_to_walk_on_the_moon_one_small_step_for_man": "Neil Armstrong blev det første menneske, der gik på Månen: \"Et lille skridt for et menneske...\"",
  "nelson_mandela_was_released_from_prison_after_27_years_a_moment_that_changed_the_world": "Nelson Mandela blev løsladt fra fængslet efter 27 år, et øjeblik der forandrede verden.",
  "november_is_the_11th_month_and_december_is_the_12th": "November er den 11. måned, og december er den 12.",
  "nut": "NØD",
  "oak": "EG",
  "one_hour_equals_60_minutes": "En time er lig med 60 minutter.",
  "oranges_are_a_type_of_fruit": "Appelsiner er en type frugt.",
  "oranges_are_citrus_fruits_full_of_vitamin_c": "Appelsiner er citrusfrugter fulde af C-vitamin.",
  "ostriches_can_fly_long_distances": "Strudse kan flyve lange afstande.",
  "ostriches_cannot_fly_but_they_can_run_very_fast": "Strudse kan ikke flyve, men de kan løbe meget hurtigt!",
  "owls_sleep_during_the_day": "Ugler sover om dagen.",
  "pan": "PANDE",
  "paris_is_in_france": "Paris ligger i Frankrig.",
  "paris_is_the_capital_city_of_france": "Paris er hovedstaden i Frankrig.",
  "penguins_are_birds_but_they_swim_instead_of_fly": "Pingviner er fugle, men de svømmer i stedet for at flyve.",
  "penguins_can_fly": "Pingviner kan flyve.",
  "penguins_live_at_the_north_pole": "Pingviner lever på Nordpolen.",
  "pine": "FYR",
  "pineapples_grow_on_low_plants_close_to_the_ground": "Ananas vokser på lave planter tæt på jorden.",
  "pineapples_grow_on_pine_trees": "Ananas vokser på fyrretræer.",
  "pink": "LYSERØD",
  "plum": "BLOMME",
  "polar_bears_live_in_the_arctic_where_it_is_very_cold": "Isbjørne lever i Arktis, hvor det er meget koldt.",
  "polar_bears_live_in_the_jungle": "Isbjørne lever i junglen.",
  "pony": "PONY",
  "poppy": "VALMUE",
  "potatoes_are_tubers_that_grow_beneath_the_soil": "Kartofler er knolde, der vokser under jorden.",
  "potatoes_grow_underground": "Kartofler vokser under jorden.",
  "prince_charles_married_lady_diana_spencer_watched_by_750_million_people_worldwide": "Prins Charles giftede sig med Lady Diana Spencer, fulgt af 750 millioner seere verden over.",
  "prince_william_married_catherine_middleton_at_westminster_abbey_watched_by_two_billion_people": "Prins William giftede sig med Catherine Middleton i Westminster Abbey, set af to milliarder mennesker.",
  "princess_diana_passed_away_in_paris_and_the_whole_world_mourned_together": "Prinsesse Diana gik bort i Paris, og hele verden sørgede sammen.",
  "princess_elizabeth_became_queen_elizabeth_ii_after_the_death_of_her_father_king_george_vi": "Prinsesse Elizabeth blev Dronning Elizabeth II efter sin far, Kong George VI's, død.",
  "princess_elizabeth_married_prince_philip_at_westminster_abbey": "Prinsesse Elizabeth giftede sig med Prins Philip i Westminster Abbey.",
  "queen_victoria_passed_away_ending_the_longest_reign_in_british_history_at_the_time": "Dronning Victoria gik bort og afsluttede den længste regeringsperiode i britisk historie på det tidspunkt.",
  "rain_falls_from_clouds": "Regn falder fra skyerne.",
  "red_means_stop_green_means_go": "Rød betyder stop — grøn betyder kør.",
  "red_orange_yellow_green_blue_indigo_and_violet": "Rød, orange, gul, grøn, blå, indigo og violet.",
  "rice": "RIS",
  "robin": "RØDHALS",
  "robins_have_a_red_breast": "Rødhalse har et rødt bryst.",
  "roses_are_flowers": "Roser er blomster.",
  "roses_are_one_of_the_most_popular_flowers_in_the_world": "Roser er en af de mest populære blomster i verden.",
  "rug": "TÆPPE",
  "run": "LØB",
  "sand": "SAND",
  "sea": "HAV",
  "sew": "SY",
  "shakespeare_was_an_english_playwright": "Shakespeare var en engelsk dramatiker.",
  "sheep_are_sheared_once_a_year_and_their_wool_is_made_into_clothing": "Får klippes en gang om året, og deres uld bruges til beklædning.",
  "sheep_give_us_wool": "Får giver os uld.",
  "sky": "HIMMEL",
  "snakes_have_legs": "Slanger har ben.",
  "snakes_slither_on_their_bellies_they_have_no_legs": "Slanger kryber på maven — de har ingen ben.",
  "snow_is_cold_it_is_frozen_water": "Sne er koldt — det er frosset vand.",
  "snow_is_hot": "Sne er varmt.",
  "son": "SØN",
  "song": "SANG",
  "spiders_are_arachnids_not_insects_they_have_8_legs_not_6": "Edderkopper er spindlere, ikke insekter — de har 8 ben, ikke 6.",
  "spiders_have_6_legs": "Edderkopper har 6 ben.",
  "spiders_have_8_legs_insects_have_6": "Edderkopper har 8 ben — insekter har 6.",
  "sputnik_the_first_satellite_was_launched_into_space_by_the_soviet_union": "Sputnik, den første satellit, blev sendt ud i rummet af Sovjetunionen.",
  "star_wars_premiered_in_cinemas_becoming_one_of_the_most_popular_films_ever_made": "Star Wars havde premiere i biograferne og blev en af de mest populære film nogensinde.",
  "strawberries_are_fruits_sweet_and_delicious": "Jordbær er frugter — søde og lækre!",
  "strawberries_are_vegetables": "Jordbær er grøntsager.",
  "sugar_is_one_of_the_sweetest_tasting_things_we_eat": "Sukker er en af de sødeste ting, vi spiser.",
  "sugar_is_sweet": "Sukker er sødt.",
  "summer_is_warmer_than_winter": "Sommer er varmere end vinter.",
  "sunflowers_turn_to_face_the_sun": "Solsikker drejer sig mod Solen.",
  "sunlight_scattering_in_the_atmosphere_makes_the_sky_look_blue": "Sollys, der spredes i atmosfæren, får himlen til at se blå ud.",
  "tea_is_a_popular_drink_in_britain": "Te er en populær drik i Storbritannien.",
  "the_1966_fifa_world_cup_began_in_england_and_england_won_it": "FIFA VM 1966 begyndte i England — og England vandt!",
  "the_aberfan_disaster_in_wales_a_community_came_together_in_the_face_of_tragedy": "Aberfan-katastrofen i Wales — et samfund stod sammen i mødet med tragedien.",
  "the_atlantic_ocean_is_between_europe_and_america": "Atlanterhavet ligger mellem Europa og Amerika.",
  "the_atlantic_ocean_separates_the_continents_of_europe_africa_and_the_americas": "Atlanterhavet adskiller Europa/Afrika og Amerika.",
  "the_beatles_appeared_on_the_ed_sullivan_show_watched_by_73_million_americans": "The Beatles optrådte i Ed Sullivan-showet, set af 73 millioner amerikanere.",
  "the_beatles_played_their_last_ever_concert_at_candlestick_park_in_san_francisco": "The Beatles spillede deres allersidste koncert på Candlestick Park i San Francisco.",
  "the_beatles_released_revolver_widely_considered_one_of_the_greatest_albums_ever": "The Beatles udgav \"Revolver,\" bredt anset som et af de bedste albums nogensinde.",
  "the_berlin_wall_officially_fell_symbolising_the_end_of_the_cold_war": "Berlinmuren faldt officielt og symboliserede afslutningen på Den Kolde Krig.",
  "the_british_drink_about_100_million_cups_of_tea_every_day": "Briterne drikker cirka 100 millioner kopper te hver dag!",
  "the_channel_tunnel_officially_opened_between_england_and_france": "Kanaltunnelen åbnede officielt mellem England og Frankrig.",
  "the_channel_tunnel_opened_connecting_britain_to_france_by_rail_for_the_first_time": "Kanaltunnelen åbnede og forbandt Storbritannien med Frankrig med jernbane for første gang.",
  "the_colour_red_means_go_in_traffic_lights": "Farven rød betyder \"kør\" i trafiklys.",
  "the_coronation_of_queen_elizabeth_ii_was_watched_by_millions_on_television": "Kroningen af Dronning Elizabeth II blev set af millioner i fjernsynet.",
  "the_earth_is_flat": "Jorden er flad.",
  "the_earth_is_round_like_a_ball": "Jorden er rund, som en bold.",
  "the_eiffel_tower_is_in_paris_france": "Eiffeltårnet er i Paris, Frankrig.",
  "the_eiffel_tower_is_in_spain": "Eiffeltårnet er i Spanien.",
  "the_encyclopaedia_britannica_ended_its_print_edition_after_244_years": "Encyclopaedia Britannica stoppede sin trykte udgave efter 244 år.",
  "the_european_robin_is_famous_for_its_bright_red_orange_breast": "Den europæiske rødhals er berømt for sit lyse rødorange bryst.",
  "the_fall_of_the_berlin_wall_began_reuniting_families_who_had_been_separated_for_decades": "Berlinmurens fald begyndte at genforene familier, der havde været adskilt i årtier.",
  "the_first_episode_of_doctor_who_was_broadcast_on_bbc_television": "Den første episode af Doctor Who blev sendt på BBC fjernsyn.",
  "the_first_space_shuttle_columbia_launched_beginning_a_new_era_of_space_travel": "Den første rumfærge \"Columbia\" blev opsendt og indledte en ny æra for rumrejser.",
  "the_five_rings_are_blue_yellow_black_green_and_red": "De fem ringe er blå, gul, sort, grøn og rød.",
  "the_great_blizzard_of_1947_began_one_of_the_worst_winters_britain_has_ever_seen": "Den store snestorm i 1947 begyndte, en af de værste vintre i Storbritanniens historie.",
  "the_great_smog_descended_on_london_for_five_days_leading_to_the_clean_air_act": "Den Store Smog lagde sig over London i fem dage, hvilket førte til loven om ren luft.",
  "the_great_wall_is_in_china_it_stretches_over_13_000_miles": "Den Kinesiske Mur er i Kina — den strækker sig over 21.000 kilometer.",
  "the_great_wall_of_china_is_in_japan": "Den Kinesiske Mur er i Japan.",
  "the_heart_pumps_blood_around_the_body": "Hjertet pumper blod rundt i kroppen.",
  "the_iconic_red_postbox_has_been_a_british_symbol_since_the_1870s": "Den ikoniske røde postkasse har været et britisk symbol siden 1870'erne.",
  "the_moon_is_made_of_cheese": "Månen er lavet af ost.",
  "the_moon_is_made_of_rock_the_cheese_idea_is_a_fun_old_tale": "Månen er lavet af sten — idéen om ost er et sjovt gammelt eventyr!",
  "the_national_health_service_nhs_was_founded_free_healthcare_for_all": "National Health Service (NHS) blev grundlagt — gratis sundhedspleje for alle.",
  "the_number_after_9_is_10": "Tallet efter 9 er 10.",
  "the_olympic_games_opened_in_london_with_danny_boyle": "De Olympiske Lege åbnede i London med Danny Boyle",
  "the_olympic_rings_have_5_colours": "De olympiske ringe har 5 farver.",
  "the_queen": "Dronningen",
  "the_queen_lives_in_buckingham_palace": "Dronningen bor på Buckingham Palace.",
  "the_river_thames_flows_through_london": "Floden Themsen løber gennem London.",
  "the_river_thames_flows_through_manchester": "Floden Themsen løber gennem Manchester.",
  "the_rms_titanic_sank_on_her_maiden_voyage_across_the_atlantic": "RMS Titanic sank på sin jomfrurejse over Atlanterhavet.",
  "the_sahara_desert_is_in_africa_it_is_the_largest_hot_desert_in_the_world": "Sahara-ørkenen er i Afrika — det er den største varme ørken i verden.",
  "the_sahara_desert_is_in_europe": "Sahara-ørkenen er i Europa.",
  "the_sky_is_usually_blue_on_a_clear_day": "Himlen er normalt blå på en klar dag.",
  "the_sun_always_rises_in_the_east_and_sets_in_the_west": "Solen står altid op i øst og går ned i vest.",
  "the_sun_rises_in_the_east": "Solen står op i øst.",
  "the_sydney_olympics_showcased_amazing_athletes_including_steve_redgrave": "OL i Sydney fremviste fantastiske atleter, heriblandt Steve Redgrave",
  "the_sydney_opera_house_was_officially_opened_after_16_years_of_construction": "Sydney Operahuset blev officielt åbnet efter 16 års byggeri.",
  "the_violin_is_a_stringed_instrument_played_with_a_bow": "Violinen er et strengeinstrument, der spilles med en bue.",
  "the_winter_olympics_were_held_in_salt_lake_city_with_record_breaking_performances": "Vinter-OL blev afholdt i Salt Lake City med rekordbrydende præstationer.",
  "the_word_breakfast_literally_means_breaking_the_fast_of_the_night": "Ordet \"breakfast\" betyder bogstaveligt \"at bryde nattens faste\".",
  "the_word_octo_means_eight": "Ordet \"okto\" betyder otte.",
  "the_world": "Verden",
  "there_are_12_months_from_january_to_december": "Der er 12 måneder fra januar til december.",
  "there_are_7_days_in_a_week": "Der er 7 dage på en uge.",
  "tide": "TIDEVAND",
  "toe": "TÅ",
  "tomatoes_are_always_purple": "Tomater er altid lilla.",
  "tune": "MELODI",
  "van": "VAREVOGN",
  "ve_day_victory_in_europe_the_end_of_world_war_ii_in_europe_was_celebrated_across_the_country": "Sejrsdag i Europa! Afslutningen på Anden Verdenskrig i Europa blev fejret over hele landet.",
  "vegetables_are_good_for_your_health": "Grøntsager er gode for helbredet.",
  "vegetables_provide_essential_vitamins_and_minerals": "Grøntsager giver vigtige vitaminer og mineraler.",
  "vj_day_victory_over_japan_marking_the_end_of_world_war_ii_entirely": "VJ-dag — Sejr over Japan, som markerede den endelige afslutning på Anden Verdenskrig.",
  "water_freezes_at_0_c": "Vand fryser ved 0°C.",
  "water_turns_to_ice_at_0_degrees_celsius": "Vand bliver til is ved 0 grader Celsius.",
  "watson_and_crick_described_the_structure_of_dna_changing_science_forever": "Watson og Crick beskrev DNA'ets struktur og ændrede videnskaben for altid.",
  "wave": "BØLGE",
  "whales_are_fish": "Hvaler er fisk.",
  "whales_are_mammals_they_breathe_air_and_feed_milk_to_their_young": "Hvaler er pattedyr — de ånder luft og giver mælk til deres unger.",
  "when_clouds_get_heavy_with_water_rain_falls_to_the_ground": "Når skyerne bliver tunge af vand, falder regnen ned på jorden.",
  "when_water_gets_cold_enough_0_c_it_freezes_into_ice": "Når vand bliver koldt nok (0°C), fryser det til is.",
  "william_shakespeare_was_born_in_stratford_upon_avon_england": "William Shakespeare blev født i Stratford-upon-Avon, England.",
  "winston_churchill_passed_away_and_the_nation_came_together_to_pay_tribute": "Winston Churchill gik bort, og nationen samlede sig for at hylde ham.",
  "wren": "GÆRDESMUTTE",
  "young_sunflowers_follow_the_sun_across_the_sky_during_the_day": "Unge solsikker følger Solen hen over himlen i løbet af dagen.",
  "your_heart_beats_about_100_000_times_a_day_to_pump_blood": "Dit hjerte slår cirka 100.000 gange om dagen for at pumpe blod.",
  "yuri_gagarin_became_the_first_human_in_space_orbiting_the_earth_in_108_minutes": "Jurij Gagarin blev det første menneske i rummet og kredsede om Jorden på 108 minutter."
};

// Apply translations to all 3 locale files
const files = [
  path.join(__dirname, '..', 'apps', 'patient-app', 'locales', 'da.json'),
  path.join(__dirname, '..', 'apps', 'caregiver-app', 'locales', 'da.json'),
  path.join(__dirname, '..', 'apps', 'caregiver-web', 'public', 'locales', 'da.json'),
];

let totalUpdated = 0;

for (const filePath of files) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  if (!data.patientApp?.stim?.gameLabels) {
    console.log(`SKIP (no gameLabels): ${filePath}`);
    continue;
  }

  let count = 0;
  for (const [key, value] of Object.entries(daTranslations)) {
    if (key in data.patientApp.stim.gameLabels) {
      data.patientApp.stim.gameLabels[key] = value;
      count++;
    }
  }

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`Updated ${count} labels in ${filePath}`);
  totalUpdated += count;
}

console.log(`\nTotal: ${totalUpdated} labels updated across ${files.length} files`);
